version: "3.7"

services:

  litecoin-client:
    image: litecoin
    container_name: litecoin
    hostname: litecoin
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - litecoin-data:/opt/data
    ports:
      - 127.0.0.1:8532:8532
    restart: always

volumes:
  litecoin-data: