---
# tasks file for prepare
- name: gather os specific variables
  include: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
  tags: vars

- name: Install the common name packages
  package:
    name:
      - mc
    state: latest
    
- name: Set hostname
  hostname:
   name: "{{ inventory_hostname }}"
- name: Cleanup /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127.0.1.1'
    state: absent
- name: Generate /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}} {{ hostvars[item].inventory_hostname_short }}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ ansible_play_hosts }}"

