---
# tasks file for ripple
- name: Creates /opt/docker directory
  file:
    path: /opt/docker
    state: directory

- copy:
    src: ripple
    dest: /opt/docker/
    owner: root
    group: root

- name: override docker-compose
  template:
    src: docker-compose.yml.j2
    dest: /opt/docker/ripple/docker-compose.yml
    owner: root
    group: root
    mode: '0644'


- name: Try to down. Fail ok for the first time
  shell: docker-compose down
  args:
    chdir: /opt/docker/ripple
  ignore_errors: True

- name: Build ripple
  shell: docker-compose build
  args:
    chdir: /opt/docker/ripple

- name: Try to start up. Fail if already started
  shell: docker-compose up -d
  args:
    chdir: /opt/docker/ripple
  ignore_errors: True
